import type { Listing } from "./types";

export const SUGGESTIONS = [
  "Toronto, ON",
  "North York",
  "Mississauga, ON",
  "Vancouver, BC",
  "Burnaby, BC",
  "Waterfront - Oakville",
  "Downtown Toronto",
  "Kitsilano",
  "Yaletown",
  "Richmond Hill",
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "L1",
    intent: "buy",
    title: "Modern Smart Home",
    address: "12 King St W",
    city: "Toronto, ON",
    neighborhood: "Downtown",
    price: 950000,
    beds: 3,
    baths: 2,
    type: "House",
    sqft: 1600,
    lotSqft: 2400,
    yearBuilt: 2019,
    status: "For Sale",
    parking: "Garage",
    energyEfficient: true,
    smartHome: true,
    ac: true,
    heating: true,
    dishwasher: true,
    washerDryer: true,
  },
  {
    id: "L2",
    intent: "rent",
    title: "Condo with EV Charger",
    address: "88 Queen St",
    city: "Toronto, ON",
    neighborhood: "Downtown",
    price: 3200,
    beds: 2,
    baths: 2,
    type: "Apartment/Condo",
    sqft: 900,
    status: "For Sale",
    parking: "Street",
    evCharger: true,
    energyStar: true,
    ac: true,
    dishwasher: true,
  },
  {
    id: "L3",
    intent: "buy",
    title: "Waterfront Townhome",
    address: "5 Marine Dr",
    city: "Oakville, ON",
    price: 1350000,
    beds: 4,
    baths: 3,
    type: "Townhouse",
    sqft: 2100,
    lotSqft: 2000,
    status: "For Sale",
    waterfront: true,
    garage: true,
    fencedYard: true,
    fireplace: true,
  },
  {
    id: "L4",
    intent: "buy",
    title: "Senior-friendly Bungalow",
    address: "21 Maple Crescent",
    city: "Mississauga, ON",
    price: 799000,
    beds: 2,
    baths: 2,
    type: "House",
    sqft: 1200,
    singleStory: true,
    ramp: true,
    wideDoorways: true,
    status: "Pending",
    parking: "Garage",
  },
  {
    id: "L5",
    intent: "buy",
    title: "Land Parcel",
    address: "Lot 4, Country Rd",
    city: "Richmond Hill, ON",
    price: 600000,
    beds: 0,
    baths: 0,
    type: "Land",
    lotSqft: 43560,
    status: "Auction",
  },
  {
    id: "L6",
    intent: "buy",
    title: "Bank Foreclosure Fixer",
    address: "9 Elm St",
    city: "Vancouver, BC",
    price: 650000,
    beds: 3,
    baths: 1.5,
    type: "House",
    sqft: 1200,
    status: "Foreclosure",
    foreclosure: true,
    parking: "Street",
  },
];
